In [1]:
import tensorflow as tf
import numpy as np

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from bokeh.plotting import figure
from bokeh.io import output_notebook, show#, output_file #Descomentar para guardar el archivo .html
from bokeh.models.widgets import Panel, Tabs
from bokeh.models import Span
output_notebook()

Loading BokehJS ...

In [4]:
X=np.asarray([[0,0],[0,1],[1,0],[1,1]])
Y=np.asarray([[0],[1],[1],[0]])

In [5]:
input_size=2
hidden_layer_size=2
output_layer_size=1
#Los placeholders son para los datos de entrada
x = tf.placeholder(tf.float32, shape=[4, input_size])
y_ = tf.placeholder(tf.float32, shape=[4, output_layer_size]) #la y real
#La variables para lo que se va a ir calculando y modificando en el camino
W_layer1=tf.Variable(tf.random_uniform([input_size,hidden_layer_size], -1, 1), name="W_layer1")
W_layer2=tf.Variable(tf.random_uniform([hidden_layer_size,output_layer_size],-1, 1), name="W_layer2")
b_layer1 = tf.Variable(tf.zeros([hidden_layer_size]), name="b_layer1")
b_layer2 = tf.Variable(tf.zeros([output_layer_size]), name="b_layer2")

In [6]:
y = tf.sigmoid(tf.matmul(x,W_layer1)+b_layer1) #la de nuestra
hip = tf.sigmoid(tf.matmul(y, W_layer2)+b_layer2)
#lossfn = tf.reduce_mean(tf.reduce_sum((y_-y)**2)) #cuadratico
lossfn= tf.reduce_mean(( (y_ * tf.log(hip)) +  
  ((1 - y_) * tf.log(1.0 - hip)) ) * -1) # cross entropy
train_step = tf.train.GradientDescentOptimizer(0.01).minimize(lossfn)

In [7]:
init = tf.initialize_all_variables()
sess = tf.Session()

In [11]:
correct_prediction = tf.equal(tf.round(hip),y_) # aca estams definiendo otras operacioes
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print(sess.run(accuracy, feed_dict={x: X, y_: Y})) # las corremos

1.0


In [55]:
sess.run(init)
while (sess.run(accuracy, feed_dict={x: X, y_: Y})) != 1.0:
    sess.run(train_step, feed_dict={x: X, y_: Y})

for i in range(50000):
    sess.run(train_step, feed_dict={x: X, y_: Y})

In [56]:
correct_prediction = tf.equal(tf.round(hip),y_) # aca estams definiendo otras operacioes
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print(sess.run(accuracy, feed_dict={x: X, y_: Y})) # las corremos

1.0


# Graficar 

In [57]:
w1=[sess.run(b_layer1, feed_dict={x: X, y_: Y})[0]]+[i[0] for i in sess.run(W_layer1, feed_dict={x: X, y_: Y})]
w2=[sess.run(b_layer2, feed_dict={x: X, y_: Y})[0]]+[i[0] for i in sess.run(W_layer2, feed_dict={x: X, y_: Y})]

In [58]:
m1=((w1[0]/w1[2]))/((-w1[0]/w1[1]))
print -w1[0]/w1[1], -w1[0]/w1[2], m1

1.48209 1.47912 -0.997995


In [59]:
m2=((w2[0]/w2[2]))/((-w2[0]/w2[1]))
print -w2[0]/w2[1], -w2[0]/w2[2], m2

0.454525 -0.427309 0.940122


In [60]:
w1

[6.7372127, -4.545764, -4.5548944]

In [61]:
w2

[-4.1673698, 9.1686268, -9.7525969]

In [75]:
intervalo = np.linspace(-0.5, 1.5, 100)
p = figure(width=750, plot_height=500, title=None)
p.circle(X[:,0],X[:,1],size=20,color=["red" if i==1 else "blue" for i in Y])
p.line(intervalo,-w1[0]/w1[2]+m1*intervalo, line_width=1.5, color="green", alpha=0.7)
p.line(intervalo,w2[0]/w2[2]-m2*intervalo, line_width=1.5, color="green", alpha=0.7)
p.title.text = "Perceptron de compuerta lógica XOR"
p.xaxis.axis_label = "X1"
p.yaxis.axis_label = "X2"
show(p)  

In [63]:
?np.linspace()

# Predicción

In [64]:
zzz = np.array([0., 0.])

In [65]:
W = sess.run(W_layer1,feed_dict={x: X, y_: Y})

In [66]:
b = sess.run(b_layer1,feed_dict={x: X, y_: Y})

In [67]:
zz = np.matmul(zzz,W) + b
zz

array([ 6.73721266,  2.52403665])

In [68]:
W2 = sess.run(W_layer2,feed_dict={x: X, y_: Y})
b2 = sess.run(b_layer2,feed_dict={x: X, y_: Y})

In [69]:
res = np.matmul(zz,W2) + b2
res

array([ 32.98770674])

In [70]:
np.round(sess.run(hip,feed_dict={x: X, y_: Y}), decimals=1)

array([[ 0.],
       [ 1.],
       [ 1.],
       [ 0.]], dtype=float32)

In [39]:
Y

array([[0],
       [1],
       [1],
       [0]])

In [71]:
y = tf.nn.softmax(tf.matmul(x,W) + b)

In [73]:
feed_dict = {x: zzz}
classification = sess.run(y, feed_dict)
print classification

ValueError: Cannot feed value of shape (2,) for Tensor u'Placeholder:0', which has shape '(4, 2)'